## makeCacheMatrix and cacheSolve work in tandem to create
## a data structure that allows for an expensive operation
## like matrix inverse to be cached and used when available

## makeCacheMatrix : Returns a data structure that works as
## input to cacheSolve. This data structure is a list of 
## functions that are used by cacheSolved(). 

makeCacheMatrix <- function(x = matrix()) {
    m <- NULL
    set <- function(y) {
        x <<- y
        m <<- NULL
    }
    get <- function() x
    setMatrixInverse <- function(solve) m <<- solve
    getMatrixInverse <- function() m
    list(set = set, get = get,
         setMatrixInverse = setMatrixInverse,
         getMatrixInverse = getMatrixInverse)

}


## cacheSolve : Returns the matrix inverse when passed the output
## generated by makeCacheMatrix().
## It tries to used the cached version of the matrix inverse,
## if none is available, it'll compute the inverse and store it.

cacheSolve <- function(x, ...) {
    ## Return a matrix that is the inverse of 'x'
    m <- x$getMatrixInverse()
    if(!is.null(m)) {
        message("getting cached data")
        return(m)
    }
    data <- x$get()
    m <- solve(data, ...)
    x$setMatrixInverse(m)
    m
}
